import Head from 'next/head'
import dynamic from 'next/dynamic'
import SideBar from '../src/components/SideBar/SideBar'

const CountryMain = dynamic(()=> import("microCountry/CountryMain"))

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex'>
        <SideBar />
        <div className='p-7'>
          <CountryMain />
        </div>
      </div>
    </>
  )
}
